### ISSUE TITLE
Ubuntu Bionic use systemd tools

### ISSUE THREAD

**Issue by baby-gnu** [OpenNebula/addon-context-linux#99] opened 2018-01-12 12:11 UTC
Hello,

I just installed an Ubuntu Bionic for tests and I found that network management is done by systemd.

* my `/etc/network/interfaces` contains only lo
* `/etc/resolv.conf` contains
```
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# 127.0.0.53 is the systemd-resolved stub resolver.
# run "systemd-resolve --status" to see details about the actual nameservers.
nameserver 127.0.0.53
```
* I have `/run/systemd/network/10-netplan-ens3.network` containing
```
[Match]
Name=ens3

[Network]
DHCP=ipv4

[DHCP]
UseMTU=true
RouteMetric=100
```

Regards.

**Comment by baby-gnu** [comment] 2018-01-12 12:21
To be more precise it use [netplan](https://insights.ubuntu.com/2017/12/01/ubuntu-bionic-netplan/)

**Comment by vholer** [comment] 2018-01-12 13:21
Closing as duplicate of #87. Thanks.

**Closed by vholer** 2018-01-12 13:21 UTC
Labels: duplicate

**Comment by baby-gnu** [comment] 2018-01-12 13:49
Erf, sorry for the noise, I looked for bionic and missed 17.10 ;-)
