### ISSUE TITLE
Growroot does not work in Debian 8 + Debian 9 with LVM

### ISSUE THREAD

**Issue by baohuy1204** [OpenNebula/addon-context-linux#110] opened 2018-04-26 07:47 UTC
When running context in Debian 8/9 with LVM, the script loc-05-grow-rootfs exit with error "Device or resource busy" and partitions are not resized correctly.
My temporary fix is create a script run before loc-05-grow-rootfs (I named it loc-04-grow-rootfs-fix):
```
#!/bin/bash

PARTED="/sbin/parted"
maxsize=$(printf %s\\n 'unit MB print list' | $PARTED | grep "Disk /dev/sda" | cut -d" " -f3 | tr -d "MB")
$PARTED /dev/sda resizepart 2 $maxsize
```
With /dev/sda2 is my / partition.

**Comment by vholer** [comment] 2018-06-18 12:02
I'm trying to reproduce, but the only problem I found is missing package dependency on the `parted`. Which is not obviously your problem, as you use the `parted` in your custom script.

Having this default LVM partition layout:

```
# lsblk 
NAME                  MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sr0                    11:0    1  366K  0 rom  
vda                   254:0    0    8G  0 disk 
├─vda1                254:1    0  243M  0 part /boot
├─vda2                254:2    0    1K  0 part 
└─vda5                254:5    0  3.8G  0 part 
  ├─debian--vg-root   253:0    0    3G  0 lvm  /
  └─debian--vg-swap_1 253:1    0  768M  0 lvm  [SWAP]
# pvs
  PV         VG        Fmt  Attr PSize PFree
  /dev/vda5  debian-vg lvm2 a--  3.76g    0 
# vgs
  VG        #PV #LV #SN Attr   VSize VFree
  debian-vg   1   2   0 wz--n- 3.76g    0 
# lvs
  LV     VG        Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  root   debian-vg -wi-ao----   3.01g                                                    
  swap_1 debian-vg -wi-ao---- 768.00m       
# df -h /
Filesystem                   Size  Used Avail Use% Mounted on
/dev/mapper/debian--vg-root  2.9G  966M  1.8G  35% /
```

I'm able to resize the root volume correctly:

```
# /bin/bash /etc/one-context.d/loc-05-grow-rootfs 
CHANGED: partition=2 start=501758 old: size=7884802 end=8386560 new: size=16275425,end=16777183
CHANGED: partition=5 start=501760 old: size=7884800 end=8386560 new: size=16275423,end=16777183
  Physical volume "/dev/vda5" changed
  1 physical volume(s) resized / 0 physical volume(s) not resized
  Size of logical volume debian-vg/root changed from 3.01 GiB (770 extents) to 7.01 GiB (1794 extents).
  Logical volume debian-vg/root successfully resized.
resize2fs 1.43.4 (31-Jan-2017)
Filesystem at /dev/mapper/debian--vg-root is mounted on /; on-line resizing required
old_desc_blocks = 1, new_desc_blocks = 1
The filesystem on /dev/mapper/debian--vg-root is now 1837056 (4k) blocks long.

# df -h /
Filesystem                   Size  Used Avail Use% Mounted on
/dev/mapper/debian--vg-root  6.9G  971M  5.6G  15% /
```

Please, provide following outputs:

* version of contextualization packages
* `lsblk`
* `pvs`, `vgs`, `lvs`
* `parted /dev/sda print`
* `cat /etc/fstab`
* and `/bin/bash -x /etc/one-context.d/loc-05-grow-rootfs` (**but, before your custom script runs!**)

to better understand the problem. The best would be to provide the image itself.

**Comment by vholer** [comment] 2020-02-17 11:55
Closing, as we were not able to reproduce the issue.

**Closed by vholer** 2020-02-17 11:55 UTC
Labels: Status: Accepted, Type: Bug
